version: '3.8'

services:
  backend:
    build:
      context: ./lanzat-backend
      dockerfile: Dockerfile
    expose:
      - "8000"
    environment:
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-https://lanzat.ignacio.tech}
      - PYTHONUNBUFFERED=1
    volumes:
      - backend-data:/app/data
    restart: always

  frontend:
    build:
      context: ./lanzat-frontend
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-https://lanzat.api.ignacio.tech}
      - NODE_ENV=production
    restart: always

volumes:
  backend-data:
